version: '3.1'

services:

    db:
        container_name: mysql
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=mysql_root
            - MYSQL_DATABASE=HOME_LEDGER_DB
            - MYSQL_USER=hl_web
            - MYSQL_PASSWORD=hl_web
        ports:
            - "3306:3306"
        volumes:
            - ./data/db/mysql:/var/lib/mysql
            
